name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: https://gitea.com/actions/checkout@v4

    - name: Set up Go
      uses: https://gitea.com/actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...