name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
#    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
#    - name: Get cleaned branch name
#      id: clean_name
#      run: |
#        # if main then say nightly otherwise cleanup name
#        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
#         echo "branch=nightly" >> "$GITHUB_OUTPUT"
#         exit 0
#        fi
#        REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\///' -e 's/release\/v//')
#        echo "branch=${REF_NAME}-nightly" >> "$GITHUB_OUTPUT"
    - name: Login to push package
      uses: docker/login-action@v3
      with:
        registry: git.leshe4ka.ru
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
    - name: build docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: git.leshe4ka.ru/webauthn/server:latest
#        tags: git.leshe4ka.ru/webauthn/server:${{ steps.clean_name.outputs.branch }}
